### ISSUE TITLE
Yarn-installed Spago doesn't work on Windows

### ISSUE THREAD

**Issue by fsoikin** [spacchetti/spago#187]
If I install Spago via Yarn (doesn't matter whether locally or globally), it seems that the shell wrappers are out of order somehow:

```
> yarn add spago
...
> npx spago
/bin/bash: C:\my_project\node_modules\.bin\..\spago\spago.exe: No such file or directory
```

At the same time, I cannot use Stack-installed Spago, because then it doesn't pick up my local Node environment, and ends up using my globally installed `purs`, which is of a different version:

```
>  spago build
spago.exe: Oh noes! It looks like the PureScript version installed on your system is
outdated for the package-set you're using.

installed version:   0.12.0
package-set version: 0.12.5

Please upgrade your `purs` version.
```

So the bottom line is: Spago is pretty much unusable to me. :-/

**Comment by f-f** [comment]
Hi @fsoikin, sorry to hear this and thanks for the report!

Unfortunately none of the maintainers here runs Windows, so we have to rely on your help to debug these issues.

Yours looks like the issue described by @GoNZooo in https://github.com/spacchetti/spago/issues/157#issuecomment-478535480
I don't have any idea myself why this might be happening. Did you try to install only with `yarn` or also `npm`? Is the behaviour the same?

Btw you might be able to use the Stack-installed version by wrapping it up in an npm script. 
Let's say you edit your `package.json` to contain
```
  "scripts": {
    ...
    "spago": "spago",
    ...
```

Then you might be able to run the global spago in the local node environment like so, e.g. to run `build`: `npm run spago -- build` (not at my computer right now so I didn't try this but I did this kind of wrapping sometimes)

**Comment by btrepp** [comment]
Hiyo.

Did you try in cmd.exe?

`yarn global add spago` installed things for me in `C:\Users\Beau\AppData\Local\Yarn\bin`.

`
C:\Users\Beau>dir C:\Users\Beau\AppData\Local\Yarn\bin
 Volume in drive C has no label.
 Volume Serial Number is BC1B-9F33

 Directory of C:\Users\Beau\AppData\Local\Yarn\bin

09-May-19  05:59 PM    <DIR>          .
09-May-19  05:59 PM    <DIR>          ..
09-May-19  05:59 PM               350 spago
09-May-19  05:59 PM                58 spago.cmd
               2 File(s)            408 bytes
               2 Dir(s)  440,973,336,576 bytes free
`

`C:\Users\Beau>C:\Users\Beau\AppData\Local\Yarn\bin\spago.cmd version
0.7.7.0
`

**Comment by btrepp** [comment]
Looking at your command, your "npx" tool might be assuming the executable is called "spago.exe". It seems "spago.cmd" or "spago" are valid instead :)

![image](https://user-images.githubusercontent.com/262933/57446363-17629980-7287-11e9-83dc-5b18b232adee.png)

**Comment by f-f** [comment]
@btrepp thanks for looking into this! Note that the CI already creates `spago.exe` files for Windows, but they are renamed to `spago` when npm installs the package, because [we specify this in the `script` key](https://github.com/spacchetti/spago/blob/93882fefa8a42582db732871a475db22aa21fdf3/npm/package.json#L15). That's why I'd like to know if the issue happens in the same way when installing with `npm` and `yarn`

Or maybe the problem is in `npx`? But google doesn't seem to find anything about it misbehaving like this 🤔

**Comment by btrepp** [comment]
```
C:\Users\Beau>npm install -g spago

> spago@0.7.7 preinstall C:\Users\Beau\AppData\Roaming\npm\node_modules\spago
> node ./install.js

C:\Users\Beau\AppData\Roaming\npm\spago -> C:\Users\Beau\AppData\Roaming\npm\node_modules\spago\spago.exe
+ spago@0.7.7
added 29 packages from 19 contributors in 15.435s

C:\Users\Beau>where spago
C:\Users\Beau\AppData\Roaming\npm\spago
C:\Users\Beau\AppData\Roaming\npm\spago.cmd
C:\Users\Beau\AppData\Local\Yarn\bin\spago
C:\Users\Beau\AppData\Local\Yarn\bin\spago.cmd
```

**Comment by f-f** [comment]
@btrepp maybe this is not even `npx`'s fault, e.g. we have the same problem just just straight npm in https://github.com/spacchetti/spago/issues/157#issuecomment-478535480

**Comment by GoNZooo** [comment]
With both terminals and WSL being overhauled and transparent integration with VSCode with everything these things might all become issues of the past. Sadly I'm unable to really weigh in now as I switched back to Linux.

**Comment by fsoikin** [comment]
Hi. Sorry for not responding for so long - very busy, head exploding.

Yes, I am seeing the same thing as @btrepp : the binaries get installed in the right locations, but without the `.exe` extensions

And yes, it works the same with with both `yarn` and `npm`, both locally and globally.

**Comment by f-f** [comment]
@fsoikin no worries!

Is it an option for you to not use `npx`? Or try the workaround from https://github.com/spacchetti/spago/issues/187#issuecomment-489728255?

**Comment by fsoikin** [comment]
Actually, scratch that. I made a mistake while verifying.

It appears that the issue is indeed with `yarn`. NPM and Yarn differ in how they generate bootstrap `.cmd` scripts for installed CLI binaries.

This is what Yarn generates:
```
@IF EXIST "%~dp0\bash.exe" (
  "%~dp0\bash.exe"  "%~dp0\..\spago\spago.exe" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  bash  "%~dp0\..\spago\spago.exe" %*
)
```

And this is NPM:
```
@"%~dp0\node_modules\spago\spago.exe"   %*
```

I'm not sure why Yarn wants to use Bash for this, and why it's relying on Bash being available on PATH.
As a result, it actually ends up being `bash.exe` from WSL, which of course cannot understand the Windows-style and Windows-rooted path, and bails.

I was ready to declare this a Yarn bug, but then I thought: "Wait a minute. `npx purs` works just fine, so why should `npx spago` fail?"

So I checked, and sure enough: the bootstrap script for `purs` (also installed with Yarn) doesn't try to run Bash, but executes `purs.bin` directly.

Why the bootstrap scripts differ - I don't know. This is where I hit the limit of my unfamiliarity with the Node ecosystem.

To answer your question: would the workaround of not using `npx` work for me?

No, it wouldn't.
First, `npx` doesn't really do that much in this case: it just ends up executing the global `spago.cmd` bootstrap script, which is also what happens if I just type `spago`. So it doesn't make a difference.
Where it _does_ make a difference is in a local environment: if I happen to have a different version of Spago installed in a local `node_modules`, I need `npx` to execute that, and not the global one.

So the bottom line is that, so far, my only workaround is to use NPM, which may actually be acceptable for the specific use case I have so far.
But I really hope this can be fixed for the long-term usability.

**Comment by f-f** [comment]
@fsoikin thanks for looking into this! I think it's good enough that we can suggest to use npm to avoid this.

Btw are on the latest version of yarn? (`v1.16.0`)
It could be that this problem is fixed in the latest.

**Comment by fsoikin** [comment]
I wasn't on the latest, but upgraded just now and checked again: still fails the same way.

The fact that bootstrap scripts are generated differently for `purs` and `spago` tells me that there must be something in _this_ repo that could be fixed, not in Yarn itself.

**Comment by f-f** [comment]
@fsoikin alright, let's document this but also keep the issue open in case anyone wants to look into this to find the root cause

**Comment by f-f** [comment]
This is being documented in #201 with the suggestion to use npm

**Comment by stkb** [comment]
While not providing the complete solution I can help a little here. Investigating it has provided some insight.

When Yarn creates both the Cmd and shellscript shims for Spago, it might create one of two 'versions': working or broken. The broken versions (since they for some reason try to run spago though bash.exe), look like this: (as noted by @fsoikin above)

Cmd:
```cmd
@IF EXIST "%~dp0\bash.exe" (
  "%~dp0\bash.exe"  "%~dp0\..\spago\spago.exe" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  bash  "%~dp0\..\spago\spago.exe" %*
)
```

Shellscript:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/bash" ]; then
  "$basedir/bash"  "$basedir/../spago/spago.exe" "$@"
  ret=$?
else 
  bash  "$basedir/../spago/spago.exe" "$@"
  ret=$?
fi
exit $ret
```

The working versions have the bash.exe-related lines removed:

Cmd:
```cmd
@"%~dp0\..\spago\spago.exe"   %*
```

Shellscript:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"$basedir/../spago/spago.exe"   "$@"
exit $?
```

### Workaround-fix ###
When you first do a `yarn add spago`, (or `yarn global add spago`) it creates the broken versions. However I've found you can fix it by doing either one of these:
- Adding *any other package* (`yarn [global] add <other-package>`)
- Removing *any other package* (`yarn [global] remove <other-package>`)

After doing one of those operations (and there are probably others), Yarn seems to re-evaluate all the shims icreated, and re-writes the spago ones, **this time with the working versions**.

### Source of the bug ###
Both NPM and Yarn use the `cmd-shim` package for all shim creation (shellscript shims too): NPM the original [npm/cmd-shim](https://github.com/npm/cmd-shim), and Yarn a newer fork: zkochan/cmd-shim ([pnpm/cmd-shim](https://github.com/pnpm/cmd-shim) on GitHub). However I couldn't find anything in the source code for that package that would cause this bug, so it seems the problem would be in Yarn's source code, which calls its api.

The only difference I can see between the PureScript and the Spago packages is that the purs executable has a `.lib` extension, whereas spago's has a normal `.exe`. It may be enough as a workaround to try changing it to `spago.lib`, though I haven't investigated that, and I feel the bug in Yarn should be fixed anyway.

### NPM ###
NPM doesn't have this particular problem; local (project) installations of spago work fine with `npx`. Though it does have another: **Spago globally-installed through NPM doesn't work in MSYS2-Bash on Windows** (in Cmd it works fine).

This is because: the `cmd-shim` package always creates either a long-version or a short-version shim for any target: the long version if the target file starts with a shebang (which executable files naturally don't), otherwise the short version.

Short version:
```sh
"$basedir/path/to/target"   "$@"
exit $?
```

The long version would be pretty much the same as the 'working' Yarn shim shown above. Only the long version works, because otherwise the `$basedir` variable isn't defined. So shellscript shims for .exe files created with NPM never work, because they are always the short versions.

As noted above, Yarn does always create the long version for .exe files; in the newer fork of `cmd-shim` that it uses, this issue has been fixed. There are open pull requests to fix it in the npm version of that repo, but that repo seems not to be maintained any more (last commit was in 2016).

### Summary ###

So in summary, both Yarn and NPM have issues with shim creation on Windows:
- If using a local (project) installation, you need to install with NPM (or use Yarn with workaround described above)
- For a global installation with and using some version of Bash, you need to install with Yarn (+ workaround)

The only fix for everything I can think of atm, that doesn't rely on upstream changes, is a little ugly: have the package's binary as a javascript file instead (with shebang), that in turn (through node) runs the real executable file.

**Comment by f-f** [comment]
Thanks @stkb for the great investigation! 👏 

I'd be fine having the JS shim calling the real executable if we can have it for Windows only (though of course the best thing would be to just have Yarn and NPM fix their issues)

**Comment by stkb** [comment]
Ok I cloned this repo to start working on a PR, and after actually looking at the contents of the dummy `spago.exe` file in `/npm`, I immediately realized why Yarn is acting the way it is:

https://github.com/spacchetti/spago/blob/87949b856d695c51110bb5b2bb996d7497d3cab4/npm/spago.exe#L1-L5

When Yarn installs the Spago package for the first time, it looks at the that dummy spago.exe file, sees the bash shebang, and creates a shim thinking it's for a bash script. The next time the shims are re-evaluated, it sees the real spago.exe which now been downloaded, and creates a (correct) shim for an .exe file instead.

Now why is Yarn already looking to/creating shims in the `preinstall` phase before we've had a chance to download our binary file? I don't know what the timings are exactly, and apparently NPM does it as we'd expect. But I'm pretty sure just removing that shebang in that file would fix the issue with Yarn (without a shebang, it would see the file as just a normal exe and create a "normal" shim).

However we still need an extra .js shim to work around all issues with NPM, unfortunately.

**Comment by f-f** [comment]
I just cut [a new release](https://github.com/spacchetti/spago/releases/tag/0.8.1.0) including the fixes from @stkb, could you all try it out to see if the issue doesn't manifest anymore?

**Comment by fsoikin** [comment]
Yes! It works perfectly well now!

Thank you very much @f-f for a quick turnaround. I am so impressed! :-)

**Comment by f-f** [comment]
Wonderful! 🎉 

You're welcome, but all credit goes to @stkb for the great fix 🙂 (and of course thank you all for helping looking into this)
