### ISSUE TITLE
Warning about Github

### ISSUE THREAD

**Issue by cscalfani** [spacchetti/spago#480]
Why am I getting the following warning:

```Warning: was not able to match url with GitHub ones: <gitlab url redacted>```

Anyone hosting their own Git Server will get this warning.

**Comment by jhrcek** [comment]
This warning was fixed recently on master (see [this change](https://github.com/spacchetti/spago/pull/453/files#diff-f232d5779e6f885e2cb557f672c29c24R68)) and the change is going to be released in spago 0.11.0.0

This warning is printed whenever repo url doesn't have the exact form `https://github.com/<ORG>/<REPO>.git` and it means the repo will not be cached in global cache (on my PC it's in `~/.cache/spago/`), but only in project local cache (in `<YOURPROJECTDIR>/.spago`).

**Comment by f-f** [comment]
Yeah I think the new form is less annoying and way clearer IMO, but still not actionable - i.e. I doesn't answer the question @cscalfani has of "how do I make this go away?"
So I think we should make it a debug log instead of printing it by default. Fix for this up in #481
